# docker-compose.yml

version: '3.8'

services:
  trade:
    build:
      context: .
      dockerfile: Dockerfile 
    hostname: trade
    platform: linux/amd64
    container_name: trade
    image: trade:latest
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 8000:8000

  postgres:
    image: postgres:15
    container_name: postgres
    hostname: postgres
    platform: linux/amd64
    environment:
        POSTGRES_DB: local_db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - .:/data
